### PR TITLE
feat: allow occam to cope with pack limitations

### PR DESCRIPTION
**Pull request by mhdawson**
pack seems to be very limited in the options it will accept when building for multi-arch. It does not
seem to accept a path with a tgz as input and only works properly if you build in an exploded directory. Otherwise it appears to have built the cnb file but the structure of the bin directory is incorrect and the executables cannot be found.

Update the jam packager to work around this by exploding the tgz after creating it and then build in that
exploded directory.

It is still a good idea to build the tgz as that
filters the files based on what is specified in the buildpack.toml.

The unit tests pass, but more integration testing might be good. Once I have confirmation that people
are comfortable withe the PR I'll manually test on a few existing buildpacks in addition to the testing I've
already done on the npm-install buildpack modified for multi-arch -> https://github.com/mhdawson/npm-install/tree/test-multi (Note that this needs an updated jam that includes an updated packit with this change - https://github.com/paketo-buildpacks/packit/pull/604)

 

## Summary

Allow the ability to test buildpacks that have been updated to support multi-arch. Occam will still only test on the one architecture as the machine the tests are run on but with the update can run tests for buildpacks that support multi-arch, or buildpacks that don't.

## Use Cases

Testing buildpacks that support multi-arch

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by mhdawson** [comment]
@robdimsdale any chance you could take a look, we need this to progress on getting Node.js buildpacks to support multi-arch.

**Comment by mhdawson** [comment]
@robdimsdale any chance you could take a look?

**Comment by mhdawson** [comment]
@ForestEckhardt, @robdimsdale any chance one of you two could take a look?

**Comment by ForestEckhardt** [comment]
Should we address this at the source (i.e. `jam`) by either adding a different flag or something instead of trying to hack around it in `occam`?

**Comment by mhdawson** [comment]
@ForestEckhardt the real fix is for pack to better support multi-arch so that all of the different options/use cases it supports for non-multiarch work but that is a much bigger effort that what is in this PR.

In this case I think jam just calls pack passing through some of the options provided by occam so it seems more confusing to me to try to add the work around in jam that says even through I called you with these pack options, convert the input and options to something else before calling pack.

**Comment by ForestEckhardt** [comment]
@mhdawson So `jam` does not call `pack` internally at all it does however produce the compressed tar file that you are unwinding. We could add a flag to only produce a directory structure which is compatible with a multi-arch build as far as I understand. We could then set that flag in `occam` until we reconcile what artifacts we are going to release with our buildpacks going forward.

**Comment by mhdawson** [comment]
I'm going to look at updating jam to see how that works out.

**Review by ForestEckhardt — APPROVED** [review]

**Pull request merged**
