### PR TITLE
Add `SourceTesting`

### PR DESCRIPTION
**Pull request by joshuatcasey**
Use `SourceTesting` instead of `Source` so that:
- It will clean up the temp dir automatically
- You don't have to check for returned errors (it will auto fail the test if there's a problem)

### CODE REVIEW

**Comment by joshuatcasey** [comment]
@paketo-buildpacks/tooling-maintainers any feedback on this?

**Comment by sophiewigmore** [comment]
I'm not entirely sure about this addition because I feel like it's not super necessary. I get it the utility of not having to clean up, but I'm not super convinced about adding it and have been hanging back on a review to see what other maintainers thought

**Comment by robdimsdale** [comment]
@joshuatcasey can you share a snippet of the changes you'd expect consuming tests to leverage? In particular, I'm interested in the propagation of `t *testing.T`. From the interface and the example test, it seems that the main change is that we would pass `t *testing.T` into the new `TestingSource` function, which automatically fails instead of returning an error.

If my understanding is correct, I think this abstraction is less clear than what we currently have. With this proposal we have a helper method that does two things - creates source and fails the test on error - instead of a single helper method that returns an error if it fails to achieve its goal. Additionally, we also pass around the `t *testing.T` which seems like a leaky abstraction.

If the goal is to automatically remove the temporary source directory, can we instead replace `destination, err := os.MkdirTemp("", "source")` with `t.TempDir()` in the existing Source function?

**Comment by joshuatcasey** [comment]
Sure. I'd personally prefer to just update `Source` rather than introduce `SourceTesting` but that would mean a breaking API change (to pass in `*testing.T`), so I introduced a new func.

As for why - it seems the strong preference of the `testing` package that these sorts of utilities clean themselves up (see `t.TempDir()`, `t.Setenv()`, etc), so I figured we could move towards that pattern.

Current:
```golang
	context("integration test", func() {
		var source string

		it.Before(func() {
			var err error
			source, err = occam.Source(filepath.Join("testdata", "default_app"))
			Expect(err).NotTo(HaveOccurred())
		})

		it.After(func() {
			Expect(os.RemoveAll(source)).To(Succeed())
		})

		it("builds with the defaults", func() {
			// does testing things
		})
	})
```

Proposed:
```golang
	context("integration test", func() {
		var source string

		it.Before(func() {
			source = occam.SourceTesting(filepath.Join("testdata", "default_app"), t)
		})

		it("builds with the defaults", func() {
			// does testing things
		})
	})
```

**Comment by robdimsdale** [comment]
Gotcha. I see that direction. I agree that it's valuable to replace `os.MkdirTemp` with `t.TempDir` throughout our tests, and I see two effective ways to achieve that goal with respect to the `occam.Source` function. Both would be new methods to preserve backwards compatibility:

1. pass in `t` as you highlight above
2. create the temp directory outside the function and pass that into the function

For clarity, the second option would look like:

```
	context("integration test", func() {
		var source string

		it.Before(func() {
			source = occam.CopySource(filepath.Join("testdata", "default_app"), t.TempDir())
		})

		it("builds with the defaults", func() {
			// does testing things
		})
	})
```
I don't really like either option, but I have a slight preference for the second. But I could easily be convinced that passing around `t` is fine.

The more I think about it, the more comfortable I am with passing around `t testing.T` into helpers. That being said, I wonder if we could have a more holistic architecture - something like `occam.WithT(t)` that sets `t` at the package for all of `occam` - that way we don't have to keep passing it around and we wouldn't break backwards compatibility (or have to create new methods) every time we identify a refactor opportunity.

**Comment by robdimsdale** [comment]
As I said above, I'm happy enough with the direction this PR is going in to continue exploring. But, it also seems like we've run out of momentum on it.

I'm going to close this to tidy up the open issues/PRs but we can re-open if we want to pick this back up.

**Pull request closed without merging**
