### PR TITLE
Add testcontainers as helper

### LINKED ISSUE #146: Adding helper for containerstructure tests
Currently `occam` offers helper for `pack` and `docker`. It might be quite useful to offer something similar for `containerstructure tests`.

see https://github.com/GoogleContainerTools/container-structure-test

With this `containerstructure tests`, it would be easy to check just built images.

e.g.:

```go
cst = NewContainerStructureTest().WithVerbose()
logs, err := cst.Run.Execute("test/my-image", "tests.yaml")
```

### LINKED ISSUE #147: Adding helper for test containers
Currently `occam` offers helper for `pack` and `docker`. It might be quite useful to offer something similar for `test containers`.

see https://github.com/testcontainers/testcontainers-go

With this `test containers`, it would be easy to test just built images.

e.g.:

```go
tc = NewTestContainers().WithEnv(map[string]string{})
logs, err := tc.Run.Execute("test/my-image")
```

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
Fixes #147 

## Summary

This PR introduces `testcontainers` as helper to ease testing buildpacks.

## Use Cases

```go
testContainer := occam.NewTestContainers()
container, err = testContainer.
                          WithExposedPorts("8080/tcp").
			  WithWaitingFor(wait.ForLog("Started App")).
			  Execute(imageName)
Expect(err).ShouldNot(HaveOccurred())
```

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by robdimsdale — COMMENTED** [review]
This generally looks good to me, but I think we're missing a test for the `testcontainer.go` file.

Also, out of curiosity, do you have an example of where you use these tools to test a buildpack? I'm not familiar with either of the tools so I'd love to learn more.

**Comment by sophiewigmore** [comment]
+1 about the test. I'm also wondering a bit about the utility of `testcontainers-go`. I think understand how the Container Structure Test addition could be helpful, but I'm not sure I fully understand the added benefit that `testcontainers-go` brings here.

**Comment by c0d1ngm0nk3y** [comment]
We use `testcontainers-go` to test the built image. If the application starts, if the port  gets served, etc. Very similar too the existing matchers for the `docker` helper. We had also some discussions if a `testcontainer-go` helper in addition to the existing `docker` helper is that useful.
It might be a good substitute, but to have both at the same time, might be more confusing than helpful.

I think, it might be a good idea to split this PR into 2 PRs, because for `ContainerStructureTests` it seems clearer to me what it adds to the table.

Regarding the test, you are of course right. The reason was that it is near to impossible to write a real and meaningful unit test for `testcontainer-go`. But maybe a test using a real container showing how to use `containertest-go` might be worth it.

**Comment by robdimsdale** [comment]
@c0d1ngm0nk3y I see why you didn't add the unit test initially - because the `testcontainers` is just a wrapper around an underlying library. I suppose you could mock out that library call, but that seems overly complex.

When I run these tests locally they are quick, so I think I'm ok with the idea of keeping them, even though they are more of an integration test than a unit test.

I notice that `TestContainers.Execute` creates a `Context.Background()` which has no deadline, and therefore relies on the go test timeout to kill the test if it hangs. I think that's probably ok but I suspect this could get frustrating when iterating on these tests in the future.

**Review by robdimsdale — DISMISSED** [review]

**Comment by loewenstein** [comment]
> We use `testcontainers-go` to test the built image. If the application starts, if the port gets served, etc. Very similar too the existing matchers for the `docker` helper. We had also some discussions if a `testcontainer-go` helper in addition to the existing `docker` helper is that useful.
> It might be a good substitute, but to have both at the same time, might be more confusing than helpful.

If we would go for substitute, it would kind of outsource the responsibility for managing integration test containers and their lifecycle to a package specialized on that, instead of investing into this realm from within the Paketo project.
Hard to say if it is worth it now, but we have made good experience with it and will likely continue to use those for integration testing regardless.

**Comment by fg-j** [comment]
@loewenstein For now, I think it'd be better for many Paketo buildpacks maintainers if we leave the `docker` helper in place. We don't have the bandwidth right now to address the tech debt of migrating all of Paketo buildpacks' existing tests to using `testcontainers-go`.

**Comment by c0d1ngm0nk3y** [comment]
> For now, I think it'd be better for many Paketo buildpacks maintainers if we leave the `docker` helper in place. We don't have the bandwidth right now to address the tech debt of migrating all of Paketo buildpacks' existing tests to using `testcontainers-go`.

@fg-j Do you think it might be still beneficial to have both? To offer the possibility and get some experience. One could then even migrate them one by one if it turns out to be beneficial. From my gut feeling, it is better to rely on a broadly used solution like `test-containers` rather than having an own solution. There might be future/special requirements which are already fulfilled by `test-containers`.

**Review by robdimsdale — DISMISSED** [review]
I'm happy with this. I don't think it introduces a significant surface area or support burden to the `occam` maintainers, and if it enables OSS consumes to leverage this testing library for their buildpacks instead of rolling their own solution I'm in favor. As pointed out by @c0d1ngm0nk3y , it also makes it easy for existing buildpacks using docker to try out the testcontainer alternative.

**Review by ForestEckhardt — DISMISSED** [review]

**Comment by ForestEckhardt** [comment]
I don't have enough reservation to keep from approving this but I am curious to see if wrapping an already existing library will have any benefits for people wanting to use `occam` over using `testcontainers` directly. I would want to keep an eye on this and make sure it does not turn into a large tech burden.

**Comment by ForestEckhardt** [comment]
@c0d1ngm0nk3y It looks like this branch needs a quick rebase

**Comment by fg-j** [comment]
🤔  Something odd seems to be happening with the commit history on this PR. I just tried to rebase to fix it up but things don't look happy. @c0d1ngm0nk3y could you try a rebase or cherry pick your commits onto a fresh branch?

**Comment by c0d1ngm0nk3y** [comment]
> 🤔 Something odd seems to be happening with the commit history on this PR. I just tried to rebase to fix it up but things don't look happy. @c0d1ngm0nk3y could you try a rebase or cherry pick your commits onto a fresh branch?

Hi @fg-j , I squashed and rebased it. It looks fine now, I guess. Please have a look.

**Review by fg-j — APPROVED** [review]

**Pull request merged**
